stages:
  preprocess:
    cmd: python cli.py data
    deps:
      - cli.py
      - illustration_colorizer
      - illustration_colorizer/conf
      - data/raw
    outs:
      - data/processed
  train:
    cmd: python cli.py train
    deps:
      - cli.py
      - illustration_colorizer
      - illustration_colorizer/conf
      - data/processed
    outs:
      - data/models
