FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml README.md ./
COPY services ./services
COPY shared ./shared

RUN uv sync --group api

EXPOSE 8000

CMD ["uv", "run", "python", "-m", "services.api.app.run"]
