FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml README.md ./
COPY services ./services
COPY shared ./shared

RUN uv sync --group bot

CMD ["uv", "run", "python", "-m", "services.bot.bot.main"]
